### ISSUE TITLE
Generate PDF doesn't work

### ISSUE THREAD

**Issue by MasterIceZ** [plumsirawit/task-pdf-writer#43]
It seems like `Generate PDF` button doesn't work. 😭 
When I clicked on a `Generate PDF` button, nothing happened.

**Comment by plumsirawit** [comment]
Uhh ok let me look into this.

**Comment by plumsirawit** [comment]
Hmm... it works for me. What happens when this button is pressed?

![image](https://user-images.githubusercontent.com/31605957/192205463-ce0bb0a1-305c-4efd-8355-2affdae32843.png)

(Expected: it should load a spinner for about 30secs - 1min and then it will automatically download a file)

**Comment by plumsirawit** [comment]
Oh sorry you said "nothing happened", so there is literally no interaction? hmm let me see

**Comment by plumsirawit** [comment]
"it works on my machine", but I don't know why it doesn't work on yours... 😭

**Comment by MasterIceZ** [comment]
[This](https://www.youtube.com/watch?v=p2lBulUJveI) is a video when I tried to create a PDF file but nothing happened. 🤔  
And I've already tried on Google Chrome, Firefox and Microsoft Edge. All of them cannot, too. 😓

**Comment by plumsirawit** [comment]
Can you try inspect element and there should be something like this
![image](https://user-images.githubusercontent.com/31605957/192410712-79435f9d-e69c-45b7-9352-5812078f1f01.png)

Let me know if some of the requests fail...

**Comment by MasterIceZ** [comment]
This image was captured when opened the document:
![image](https://user-images.githubusercontent.com/64594596/192411601-85a14123-9d87-4fa9-b751-4ece7bb87101.png)
And this was captured after I clicked a `create PDF` button.
![image](https://user-images.githubusercontent.com/64594596/192411929-37250827-fa3b-4869-b57c-80ae1462225e.png)

**Comment by plumsirawit** [comment]
Hmmm let me see

**Comment by plumsirawit** [comment]
How about the console? Is there any error message?

**Comment by MasterIceZ** [comment]
There is an error. 🙏🏻 
![image](https://user-images.githubusercontent.com/64594596/192421548-2458d461-8f5e-4565-965b-0f351d985707.png)

**Comment by plumsirawit** [comment]
ahhhhh i c

**Comment by MasterIceZ** [comment]
When full title is Thai langauge, it will crash. 🤔

**Comment by plumsirawit** [comment]
Ok, I've reproduced the bug. It was due to some metadata (i.e. task name or contest name) being non ISO-8859-1 (i.e. non English character). I'll produce a fix soon but for now the workaround is to change non-English metadata to English first. I'll do a PR attaching this issue.

**Comment by plumsirawit** [comment]
Note to self: hmmm maybe metadata is not good for the long-term usage. In the future if we have time let's migrate to some DynamoDB (or just simply create another file in S3 containing the metadata, maybe in json using utf-8).

**Comment by plumsirawit** [comment]
Note to self: Found a solution: use minimal metadata and let the lambda fetch more data from firebase rather than s3 metadata.
