### ISSUE TITLE
PDF Generation bugged in AWS Lambda

### ISSUE THREAD

**Issue by plumsirawit** [plumsirawit/task-pdf-writer#9]
Preview: [document.pdf](https://github.com/plumsirawit/task-pdf-writer/files/6812185/document.2.pdf)

The margin should be beautifully formatted, there shouldn't be scrollbars, etc.

**Comment by plumsirawit** [comment]
Possible cause: Xvfb isn't used in this case. [Possible fix.](https://forums.aws.amazon.com/thread.jspa?messageID=688416)

**Comment by plumsirawit** [comment]
Current plan: use python in lambda instead of nodejs (switch the whole serverless framework language) to make the code as likely the same as original as possible

**Comment by porames** [comment]
น่าสนใจครับ

**Comment by plumsirawit** [comment]
Definite cause investigated. I confirm that it is about xvfb. Python attempt works well in local.

**Comment by plumsirawit** [comment]
Xvfb didn't start (using custom layer). Current workaround: use dockerized runtime instead of python. Installing xvfb and wkhtmltopdf would be easy now, no need for layers.

**Comment by plumsirawit** [comment]
Docker solution satisfies the requirements. :rocket:
